a = input("Digite algo: ")
print(type(a))
print("É numérico? ", a.isnumeric())
print("É alfabético? ", a.isalpha())
print("É alfanumérico? ", a.isalnum())
print("É upper case? ", a.isupper())
print("É lower case? ", a.islower())
